# Site settings
title:  Adam Komisarek's rants
email: contact@akomisarek.com
description: > # this means to ignore newlines until "baseurl:"
  This is yet another software development blog on the Internet.
  I will write about interesting stuff I have encountered during my work or other projects.
  If I help save your time I will be happy!  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://akomisarek.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: 

# Build settings
markdown: kramdown
